/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-background": "#F5FAF8",
        "tertiary-fixed-dim": "#c0c6db",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#404758",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#A0A7A5",
        "on-surface": "#F5FAF8",
        error: "#ba1a1a",
        "on-primary": "#ffffff",
        "inverse-primary": "#6bd8cb",
        "primary-container": "#008378",
        "surface-container-low": "#1E1E1E",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#f4fffc",
        "inverse-surface": "#2c3130",
        "tertiary-fixed": "#dce2f7",
        "on-tertiary-fixed": "#141b2b",
        "on-tertiary-container": "#fefcff",
        "on-primary-fixed-variant": "#005049",
        primary: "#6bd8cb",
        "primary-fixed-dim": "#6bd8cb",
        background: "#121212",
        "surface-dim": "#1E1E1E",
        "surface-container-highest": "#333938",
        "surface-container-high": "#2A2F2E",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#edf2f0",
        "error-container": "#ffdad6",
        "secondary-container": "#1E1E1E",
        "surface-bright": "#1E1E1E",
        secondary: "#585f6c",
        "on-secondary-container": "#A0A7A5",
        "surface-container": "#1E1E1E",
        "secondary-fixed-dim": "#c0c7d6",
        "surface-container-lowest": "#000000",
        "primary-fixed": "#89f5e7",
        "tertiary-container": "#6e7487",
        tertiary: "#555c6e",
        outline: "#6d7a77",
        "on-secondary-fixed-variant": "#404754",
        "surface-tint": "#006a61",
        "surface-variant": "#333938",
        "on-primary-fixed": "#00201d",
        "outline-variant": "#3d4947",
        "on-secondary-fixed": "#151c27",
        surface: "#121212",
        "secondary-fixed": "#dce2f3",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        base: "4px",
        md: "16px",
        sm: "8px",
        "margin-mobile": "16px",
        xs: "4px",
        xl: "32px",
        "gutter-mobile": "12px",
        lg: "24px",
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "display-lg": ["Inter"],
        "body-md": ["Inter"],
        "headline-md": ["Inter"],
        "body-sm": ["Inter"],
        "headline-sm": ["Inter"],
        "display-lg-mobile": ["Inter"],
        "label-sm": ["Inter"],
        "label-md": ["Inter"],
      },
      fontSize: {
        "body-lg": ["18px", {lineHeight: "28px", fontWeight: "400"}],
        "display-lg": [
          "32px",
          {lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700"},
        ],
        "body-md": ["16px", {lineHeight: "24px", fontWeight: "400"}],
        "headline-md": [
          "24px",
          {lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600"},
        ],
        "body-sm": ["14px", {lineHeight: "20px", fontWeight: "400"}],
        "headline-sm": [
          "20px",
          {lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600"},
        ],
        "display-lg-mobile": [
          "28px",
          {lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700"},
        ],
        "label-sm": ["12px", {lineHeight: "16px", fontWeight: "500"}],
        "label-md": [
          "14px",
          {lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500"},
        ],
      },
    },
  },
  plugins: [],
};
